name: mbr-mt
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - sacremoses
  - sacrebleu
  - pandas
  - isort
  - black
  - ruff
  - mypy
  - tqdm
  - ipykernel
  - pyarrow
  - sentencepiece
  - transformers
  - pip:
    - cltk
    - subword-nmt
    - tensor2tensor
