name: black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Harmonizing code style with black
      run: |
        for file in $(git ls-files '*.py') do
          black file --line-length 100 --skip-string-normalization
        done
